### ISSUE TITLE
Pruning doesn't work as intended when running Vorta as a container

### ISSUE THREAD

**Issue by Znerox** [borgbase/vorta-docker#17]
For a long time, I've noticed that pruning doesn't seem to make my repository any smaller. It turns out that under "Archives", "Prune Options and Archive Naming", "Prune Prefix" is set to it's default value, "{hostname}-". 

The problem is that the hostname changes every time the docker image gets updated. So the pruning process only considers the backups that have been uploaded since the image was last updated, anything older gets left on the repository / backup target. I suggest that when running in a container, the default value for "Prune Prefix" should be blank.

**Comment by Ranbato** [comment]
Good catch.  I never encountered this because I always set a hostname on my containers.
After looking into this, I don't see an easy way to change this default without setting up code to check to see if this is the first startup of the container, editing the config file after Vorta creates it, etc.  I'm not sure that there is a safe way to do this programatically without risking breaking values that people set manually in Vorta.

I think the best solution at this point is to add to the documentation and examples this information and recommend that a `hostname `always be set.  Setting the hostname on container run eliminates the problem.

For your specific situation or anyone else experiencing it, you'll want to remove the hostname value until you add the `hostname`
